### ISSUE TITLE
ошибка при получении журнала (studenttotal)

### ISSUE THREAD

**Issue by f1xxd** [lentryd/NetSchoolApi#20]
**Описание проблемы**
при получении журнала, используя метод .journal() возникает ошибка в функции getTaskId(), апи СГ возвращает статус 409 (ошибка авторизации)

**Шаги для воспроизведения**
1. await user.logIn()
2. await user.journal() - возникает ошибка
3. await user.logOut()

**Скриншоты/Логи**
сейчас возможности приложить нет, если это чем то может помочь приложу чуть позже

**(пожалуйста, заполните следующую информацию):**
 - Среда: Arch Linux
 - Версия NodeJS: 22.12.0
 - Версия библиотеки: 1.11.0

**Дополнительная информация**
ошибка типа 409 http://sgo.volganet.ru/webapi/v2/reports/studenttotal/queue
посмотрел запросы к моему сетевому, как я понял там без webapi в адресе получается, попробовал исправить, но ничем не помогло

**Comment by lentryd** [comment]
> **Скриншоты/Логи**
> сейчас возможности приложить нет, если это чем то может помочь приложу чуть позже

Всё-таки лучше прикрепить логи, так немного понятнее будет

**Comment by f1xxd** [comment]
![image](https://github.com/user-attachments/assets/10909090-9187-493c-9b63-6eb1f7dd7015)

**Comment by f1xxd** [comment]
> посмотрел запросы к моему сетевому, как я понял там без webapi в адресе получается

сейчас посмотрел, проблема не в этом
![image](https://github.com/user-attachments/assets/6d553137-f5c2-4c11-8f14-ca55ef24ee47)

**Comment by lentryd** [comment]
Попробуй обновить версию либы, возможно поможет (но не факт)

**Comment by f1xxd** [comment]
на 1.12.0 попробовал, то же самое

**Comment by lentryd** [comment]
Ты какие-то параметры передаешь в функцию journal?

**Comment by f1xxd** [comment]
![image](https://github.com/user-attachments/assets/0d690da9-c282-4546-a3cd-78dca8a77020)
нет

**Comment by lentryd** [comment]
Возможно в твоей версии сетевого что-то сделали. Т.к. у других людей все работает. Можешь попробовать самостоятельно разобрать что нет так. Сравнить какие данные отправляются в браузере и какие данные отправляет либа

**Comment by f1xxd** [comment]
да понимаю что дело в моем сетевом, фиксить пробовал, но результата никакого, именно в очереди ошибка
попробую пофиксить, если что сюда докину либо пр создам

**Comment by lentryd** [comment]
> попробую пофиксить, если что сюда докину либо пр создам

Хорошо, удачи 😉

**Comment by f1xxd** [comment]
сейчас вопрос возник, signalr/negotiate используется в новой версии репортов или остался в старой?
версия моего сетевого 5.32.74185.64, в reportFile/index.ts к signalr/negotiate не обращаются, а в легаси он есть

**Comment by f1xxd** [comment]
запросы сетевого
![image](https://github.com/user-attachments/assets/888dcf07-1692-4878-a0b6-aa284b67dce9)

legacy.ts
![image](https://github.com/user-attachments/assets/c08d932d-4143-4734-805c-9d77c08b0d29)

reportFile/index.ts
![image](https://github.com/user-attachments/assets/bee6aafd-defe-43ae-823a-b4dc4774b661)

**Comment by lentryd** [comment]
Какая у тебя версия сетевого?

**Comment by f1xxd** [comment]
![image](https://github.com/user-attachments/assets/53f36ddb-348a-422b-a855-594a73514a6c)
ну после такого не проходит все равно)

**Comment by f1xxd** [comment]
> не проходит все равно

![image](https://github.com/user-attachments/assets/758eb382-6667-4f85-b9fb-546049d8e5bd)

**Comment by lentryd** [comment]
Они что решили перенести в новую версию код из старой и собрать Франкенштейна

**Comment by f1xxd** [comment]
все возможно, я каждый раз удивляюсь с того что там творится

**Comment by f1xxd** [comment]
> запросы сетевого
> ![image](https://private-user-images.githubusercontent.com/68644513/392498474-888dcf07-1692-4878-a0b6-aa284b67dce9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzMxNzgsIm5iZiI6MTczMzMzMjg3OCwicGF0aCI6Ii82ODY0NDUxMy8zOTI0OTg0NzQtODg4ZGNmMDctMTY5Mi00ODc4LWEwYjYtYWEyODRiNjdkY2U5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE3MjExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MzJmY2VhNTI3OWYyMTBjNjBiY2UwYzY0YjgxMjlhMDZlNTUwODE5Mzk3MWNlNzA2ZjFmYjE1ZGE1YmI4NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zZ1-YfFTempqhTfR8hulgfloqQBk_6O2LduGqkINyv4)

я заметил что queue вызывается после всего действия уже, а в коде перед подключением к вебсокету
посмотрел где используется taskId, и посмотрел в запросах сетевого
![image](https://github.com/user-attachments/assets/ec85d9a6-8926-4a2d-bb0f-40d6d9c8d81a)
и понял что он там вообще не нужен

в коде сделал его также []
![image](https://github.com/user-attachments/assets/bf17e080-8d29-4fae-bb38-aa5cf15ee109)

но ошибка также осталась, просто уже другая
![image](https://github.com/user-attachments/assets/7e16e48c-2a88-426e-bd62-7bf66d975a7f)

**Comment by f1xxd** [comment]
а нет, не туда посмотрел
![image](https://github.com/user-attachments/assets/16fc4624-5083-4af0-bdcd-45e7a95d1eaf)
все таки используется

**Comment by f1xxd** [comment]
![image](https://github.com/user-attachments/assets/87eb0895-1a01-4988-ae7a-9c7acdbad454)
а еще вот где прикол, версия больше 5.24.0.0 но репорт-в2 есть

**Comment by lentryd** [comment]
> ![image](https://github.com/user-attachments/assets/87eb0895-1a01-4988-ae7a-9c7acdbad454)
> а еще вот где прикол, версия больше 5.24.0.0 но репорт-в2 есть

Он вроде как раз в районе 5.24 появился. Раньше в нем были логнполли, но от них отказались

**Comment by KOTOKOPOLb** [comment]
сейчас и у меня перестали формироваться отчёты, получаю
```js
Error: Unknown error.
Error: 
    at /workspace/NetSchoolBot/node_modules/netschoolapi/dist/methods/reportFile/index.js:158:32
    at Generator.next (<anonymous>)
    at /workspace/NetSchoolBot/node_modules/netschoolapi/dist/methods/reportFile/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/workspace/NetSchoolBot/node_modules/netschoolapi/dist/methods/reportFile/index.js:4:12)
    at WebSocket.<anonymous> (/workspace/NetSchoolBot/node_modules/netschoolapi/dist/methods/reportFile/index.js:130:49)
    at Object.onceWrapper (node:events:632:26)
    at WebSocket.emit (node:events:517:28)
    at WebSocket.emitClose (/workspace/NetSchoolBot/node_modules/ws/lib/websocket.js:262:12)
    at emitErrorAndClose (/workspace/NetSchoolBot/node_modules/ws/lib/websocket.js:1042:13)
```
версия сго: 5.32.74326.117

**Comment by lentryd** [comment]
Значит в новой версии что-то сделали, если сможете исправить, то пишите

**Comment by lentryd** [comment]
@KOTOKOPOLb @f1xxd, есть успехи? Вроде как там полностью заблокировали апи для авторизации по логину/паролю

**Comment by KOTOKOPOLb** [comment]
Пока не смог исправить получение отчёта, а на счёт апи - не знаю, у меня пока всё работает (вход, получение дз, расписания работают точно)

**Comment by lentryd** [comment]
> на счёт апи - не знаю, у меня пока всё работает

Хм, может ещё не обновили систему. Ну ладно посмотрим что будет в будущем)

**Comment by f1xxd** [comment]
> Вроде как там полностью заблокировали апи для авторизации по логину/паролю

с 1 января отключают, надо с госуслугами думать что-то
по отчетам пока ничего не делаю, бредятина полная

**Comment by KOTOKOPOLb** [comment]
> с 1 января отключают, надо с госуслугами думать что-то по отчетам пока ничего не делаю, бредятина полная

Сомнительно, нам пока ничего такого не сообщали. Ну посмотрим, мб не во всех регионах такое

**Comment by lentryd** [comment]
> сейчас и у меня перестали формироваться отчёты, получаю
> 
> Error: Unknown error.
> Error: 
>     at /workspace/NetSchoolBot/node_modules/netschoolapi/dist/methods/reportFile/index.js:158:32
>     at Generator.next (<anonymous>)
>     at /workspace/NetSchoolBot/node_modules/netschoolapi/dist/methods/reportFile/index.js:8:71
>     at new Promise (<anonymous>)
>     at __awaiter (/workspace/NetSchoolBot/node_modules/netschoolapi/dist/methods/reportFile/index.js:4:12)
>     at WebSocket.<anonymous> (/workspace/NetSchoolBot/node_modules/netschoolapi/dist/methods/reportFile/index.js:130:49)
>     at Object.onceWrapper (node:events:632:26)
>     at WebSocket.emit (node:events:517:28)
>     at WebSocket.emitClose (/workspace/NetSchoolBot/node_modules/ws/lib/websocket.js:262:12)
>     at emitErrorAndClose (/workspace/NetSchoolBot/node_modules/ws/lib/websocket.js:1042:13)
> версия сго: 5.32.74326.117

Вот решение этой проблемы https://github.com/lentryd/NetSchoolApi/issues/22#issuecomment-2770282324
